//
// Attachment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Attachment: Codable {


    public var _id: UUID?

    public var uri: URI?

    public init(_id: UUID?, uri: URI?) { 
        self._id = _id
        self.uri = uri
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case uri
    }


}

