//
// CombinationConstraintEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CombinationConstraintEntry: Codable {

    public enum Allow: String, Codable { 
        case _none = "none"
        case all = "all"
    }    /** base rule */
    public var allow: Allow?

    public var except: SparseIdArray?

    public init(allow: Allow?, except: SparseIdArray?) { 
        self.allow = allow
        self.except = except
    }


}

