//
// DateTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** ISO 8601:2004 date and time in UTC or with a specific offset */

public struct DateTime: Codable {



}

