//
// EntryType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum EntryType: String, Codable {
    case activity = "activity"
    case expense = "expense"

}
