//
// EntryStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum EntryStatus: String, Codable {
    case draft = "draft"
    case synchronizing = "synchronizing"
    case processing = "processing"
    case processed = "processed"
    case failed = "failed"

}
