//
// EnumerationType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum EnumerationType: String, Codable {
    case project = "project"
    case workPackage = "work_package"
    case serviceCode = "service_code"
    case absenceType = "absence_type"
    case expenseType = "expense_type"
    case userfieldDefinition = "userfield_definition"
    case currency = "currency"

}
