//
// EnumeratorConstraints.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** additional enumerator constraints */

public struct EnumeratorConstraints: Codable {


    public var enumeratorType: EnumerationType

    public var enumeratorId: ObjectId

    /** for local constraint representation */
    public var assignableIn: [EntryType]?

    public var entrySchemes: Dictionary?

    /** maps another EnumerationType to a restriction rule */
    public var combinationConstraints: Dictionary?

    public init(enumeratorType: EnumerationType, enumeratorId: ObjectId, assignableIn: [EntryType]?, entrySchemes: Dictionary?, combinationConstraints: Dictionary?) { 
        self.enumeratorType = enumeratorType
        self.enumeratorId = enumeratorId
        self.assignableIn = assignableIn
        self.entrySchemes = entrySchemes
        self.combinationConstraints = combinationConstraints
    }


}

