//
// FormattedString.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FormattedString: Codable {


    /** global identifier for a translatable format string */
    public var formatStringId: Int?

    /** untranslated default format string, which must take all arguments provided in formatStringArgs, if any */
    public var defaultFormatString: String

    /** format string args for defaultFormatString or the format string identified by formatStringId */
    public var formatStringArgs: [Object]?

    public init(formatStringId: Int?, defaultFormatString: String, formatStringArgs: [Object]?) { 
        self.formatStringId = formatStringId
        self.defaultFormatString = defaultFormatString
        self.formatStringArgs = formatStringArgs
    }


}

