//
// InputFormat.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** input format specifier */
public enum InputFormat: String, Codable {
    case scalar = "SCALAR"
    case range = "RANGE"

}
