//
// Location.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Location: Codable {


    public var latitude: BigDecimal?

    public var longitude: BigDecimal?

    public var name: String?

    public var premise: String?

    public var subpremise: String?

    public var address: Address?

    public init(latitude: BigDecimal?, longitude: BigDecimal?, name: String?, premise: String?, subpremise: String?, address: Address?) { 
        self.latitude = latitude
        self.longitude = longitude
        self.name = name
        self.premise = premise
        self.subpremise = subpremise
        self.address = address
    }


}

