//
// ProblemDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** https://tools.ietf.org/html/draft-nottingham-http-problem-06#section-3 */

public struct ProblemDetails: Codable {


    /** An absolute URI [RFC3986] that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html401-19991224]). When this member is not present, its value is assumed to be \&quot;about:blank\&quot;.  */
    public var type: String?

    /** A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localisation.  */
    public var title: String?

    /** The HTTP status code ([RFC2616], Section 6) generated by the origin server for this occurrence of the problem.  */
    public var status: Int?

    /** An human readable explanation specific to this occurrence of the problem.  */
    public var detail: String?

    /** An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.  */
    public var instance: String?

    public init(type: String?, title: String?, status: Int?, detail: String?, instance: String?) { 
        self.type = type
        self.title = title
        self.status = status
        self.detail = detail
        self.instance = instance
    }


}

