//
// Time.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** ISO 8601:2004 time with a time offset */

public struct Time: Codable {



}

