//
// Unit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A subset of UCUM codes with a descriptive name.  UCUM Specification: http://unitsofmeasure.org/ucum.html  */

public struct Unit: Codable {

    public enum Code: String, Codable { 
        case d = "d"
        case h = "h"
        case min = "min"
        case km = "km"
        case _1 = "1"
    }    /** The ucum code. See following sections in the UCUM specification: * TABLES OF TERMINAL SYMBOLS / PREFIXES * TABLES OF TERMINAL SYMBOLS / BASE UNITS * EXAMPLES FOR SOME NON-UNITS  */
    public var code: Code

    public var descriptiveName: String?

    public init(code: Code, descriptiveName: String?) { 
        self.code = code
        self.descriptiveName = descriptiveName
    }


}

