//
// ClikAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class ClikAPI { 
    /**
     Create or update one or multiple entries independently
     
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createOrUpdateEntries(body: [Entry]? = nil, completion: @escaping ((_ data: [Entry]?,_ error: Error?) -> Void)) {
        createOrUpdateEntriesWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create or update one or multiple entries independently
     - POST /mandants/{mandant}/entries
     - OAuth:
       - type: oauth2
       - name: oauth2
     
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<[Entry]> 
     */
    open class func createOrUpdateEntriesWithRequestBuilder(body: [Entry]? = nil) -> RequestBuilder<[Entry]> {
        let path = "/mandants/{mandant}/entries"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Entry]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: )
    }


    /**
     Delete a an entry by id
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteEntryById(completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        deleteEntryByIdWithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Delete a an entry by id
     - DELETE /mandants/{mandant}/entries/{id}
     - OAuth:
       - type: oauth2
       - name: oauth2

     - returns: RequestBuilder<Void> 
     */
    open class func deleteEntryByIdWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/mandants/{mandant}/entries/{id}"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: )
    }


    /**
     * enum for parameter combinationConstraints
     */
    public enum _getEnumerationConstraints: Bool { 
    }

    /**
     * enum for parameter mandant
     */
    public enum _getEnumerationConstraints: String { 
    }

    /**
     * enum for parameter enumeratorType
     */
    public enum _getEnumerationConstraints: EnumerationType { 
    }

    /**
     * enum for parameter xPage
     */
    public enum _getEnumerationConstraints: String { 
    }

    /**
     * enum for parameter xPageSize
     */
    public enum _getEnumerationConstraints: Int { 
    }

    /**
     Read constraints for a single enumerator
     
     - parameter combinationConstraints: (query) Includes/excludes the property combinationConstraints. Must be set explicitly to false for performance reasons.  
     - parameter mandant: (path) The mandant to operate on 
     - parameter enumeratorType: (path) The enumerator type to retrieve restrictions for 
     - parameter xPage: (header) A server defined page reference returned in the header \&quot;x-next-page\&quot; (optional)
     - parameter xPageSize: (header) How many items to return in a page (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getEnumerationConstraints(combinationConstraints: _getEnumerationConstraints, mandant: _getEnumerationConstraints, enumeratorType: _getEnumerationConstraints, xPage: _getEnumerationConstraints? = nil, xPageSize: _getEnumerationConstraints? = nil, completion: @escaping ((_ data: [EnumeratorConstraints]?,_ error: Error?) -> Void)) {
        getEnumerationConstraintsWithRequestBuilder(combinationConstraints: combinationConstraints, mandant: mandant, enumeratorType: enumeratorType, xPage: xPage, xPageSize: xPageSize).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Read constraints for a single enumerator
     - GET /mandants/{mandant}/enumeratorConstraints/{enumeratorType}/
     - OAuth:
       - type: oauth2
       - name: oauth2
     - responseHeaders: [x-next-page(String)]
     
     - parameter combinationConstraints: () Includes/excludes the property combinationConstraints. Must be set explicitly to false for performance reasons.  
     - parameter mandant: (path) The mandant to operate on 
     - parameter enumeratorType: (path) The enumerator type to retrieve restrictions for 
     - parameter xPage: (header) A server defined page reference returned in the header \&quot;x-next-page\&quot; (optional)
     - parameter xPageSize: (header) How many items to return in a page (optional)

     - returns: RequestBuilder<[EnumeratorConstraints]> 
     */
    open class func getEnumerationConstraintsWithRequestBuilder(combinationConstraints: _getEnumerationConstraints, mandant: _getEnumerationConstraints, enumeratorType: _getEnumerationConstraints, xPage: _getEnumerationConstraints? = nil, xPageSize: _getEnumerationConstraints? = nil) -> RequestBuilder<[EnumeratorConstraints]> {
        var path = "/mandants/{mandant}/enumeratorConstraints/{enumeratorType}/"
        let mandantPreEscape = "\(mandant.rawValue)"
        let mandantPostEscape = mandantPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{mandant}", with: mandantPostEscape, options: .literal, range: nil)
        let enumeratorTypePreEscape = "\(enumeratorType.rawValue)"
        let enumeratorTypePostEscape = enumeratorTypePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{enumeratorType}", with: enumeratorTypePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "combinationConstraints": combinationConstraints.rawValue
        ])
        let nillableHeaders: [String: Any?] = [
            "x-page": xPage?.rawValue,
            "x-page-size": xPageSize?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[EnumeratorConstraints]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: , headers: headerParameters)
    }


    /**
     * enum for parameter mandant
     */
    public enum _listEntries: String { 
    }

    /**
     * enum for parameter status
     */
    public enum _listEntries: String { 
    }

    /**
     * enum for parameter startDate
     */
    public enum _listEntries: Date { 
    }

    /**
     * enum for parameter xPage
     */
    public enum _listEntries: String { 
    }

    /**
     * enum for parameter xPageSize
     */
    public enum _listEntries: Int { 
    }

    /**
     List entries
     
     - parameter mandant: (path) The mandant to operate on 
     - parameter status: (query) One or more statuses (disjunctive) (optional)
     - parameter startDate: (query) The minimum date of entries (optional)
     - parameter xPage: (header) A server defined page reference returned in the header \&quot;x-next-page\&quot; (optional)
     - parameter xPageSize: (header) How many items to return in a page (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listEntries(mandant: _listEntries, status: [EntryStatus]? = nil, startDate: _listEntries? = nil, xPage: _listEntries? = nil, xPageSize: _listEntries? = nil, completion: @escaping ((_ data: [Entry]?,_ error: Error?) -> Void)) {
        listEntriesWithRequestBuilder(mandant: mandant, status: status, startDate: startDate, xPage: xPage, xPageSize: xPageSize).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List entries
     - GET /mandants/{mandant}/entries
     - OAuth:
       - type: oauth2
       - name: oauth2
     - responseHeaders: [x-next-page(String)]
     
     - parameter mandant: (path) The mandant to operate on 
     - parameter status: () One or more statuses (disjunctive) (optional)
     - parameter startDate: () The minimum date of entries (optional)
     - parameter xPage: (header) A server defined page reference returned in the header \&quot;x-next-page\&quot; (optional)
     - parameter xPageSize: (header) How many items to return in a page (optional)

     - returns: RequestBuilder<[Entry]> 
     */
    open class func listEntriesWithRequestBuilder(mandant: _listEntries, status: [EntryStatus]? = nil, startDate: _listEntries? = nil, xPage: _listEntries? = nil, xPageSize: _listEntries? = nil) -> RequestBuilder<[Entry]> {
        var path = "/mandants/{mandant}/entries"
        let mandantPreEscape = "\(mandant.rawValue)"
        let mandantPostEscape = mandantPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{mandant}", with: mandantPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": status, 
        ])
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "startDate": startDate?.rawValue
        ])
        let nillableHeaders: [String: Any?] = [
            "x-page": xPage?.rawValue,
            "x-page-size": xPageSize?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Entry]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: , headers: headerParameters)
    }


    /**
     * enum for parameter mandant
     */
    public enum _listEnumerators: String { 
    }

    /**
     * enum for parameter type
     */
    public enum _listEnumerators: EnumerationType { 
    }

    /**
     * enum for parameter parentProject
     */
    public enum _listEnumerators: String { 
    }

    /**
     * enum for parameter xPage
     */
    public enum _listEnumerators: String { 
    }

    /**
     * enum for parameter xPageSize
     */
    public enum _listEnumerators: Int { 
    }

    /**
     List enumerators
     
     - parameter mandant: (path) The mandant to operate on 
     - parameter type: (path) The enumerator type 
     - parameter parentProject: (query) The parent project to filter by (optional)
     - parameter xPage: (header) A server defined page reference returned in the header \&quot;x-next-page\&quot; (optional)
     - parameter xPageSize: (header) How many items to return in a page (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listEnumerators(mandant: _listEnumerators, type: _listEnumerators, parentProject: _listEnumerators? = nil, xPage: _listEnumerators? = nil, xPageSize: _listEnumerators? = nil, completion: @escaping ((_ data: [Enumerator]?,_ error: Error?) -> Void)) {
        listEnumeratorsWithRequestBuilder(mandant: mandant, type: type, parentProject: parentProject, xPage: xPage, xPageSize: xPageSize).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List enumerators
     - GET /mandants/{mandant}/enumerators/{type}
     - OAuth:
       - type: oauth2
       - name: oauth2
     - responseHeaders: [x-next-page(String)]
     
     - parameter mandant: (path) The mandant to operate on 
     - parameter type: (path) The enumerator type 
     - parameter parentProject: () The parent project to filter by (optional)
     - parameter xPage: (header) A server defined page reference returned in the header \&quot;x-next-page\&quot; (optional)
     - parameter xPageSize: (header) How many items to return in a page (optional)

     - returns: RequestBuilder<[Enumerator]> 
     */
    open class func listEnumeratorsWithRequestBuilder(mandant: _listEnumerators, type: _listEnumerators, parentProject: _listEnumerators? = nil, xPage: _listEnumerators? = nil, xPageSize: _listEnumerators? = nil) -> RequestBuilder<[Enumerator]> {
        var path = "/mandants/{mandant}/enumerators/{type}"
        let mandantPreEscape = "\(mandant.rawValue)"
        let mandantPostEscape = mandantPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{mandant}", with: mandantPostEscape, options: .literal, range: nil)
        let typePreEscape = "\(type.rawValue)"
        let typePostEscape = typePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{type}", with: typePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "parentProject": parentProject?.rawValue
        ])
        let nillableHeaders: [String: Any?] = [
            "x-page": xPage?.rawValue,
            "x-page-size": xPageSize?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Enumerator]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: , headers: headerParameters)
    }


    /**
     Read an entry by its id
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func readEntry(completion: @escaping ((_ data: Entry?,_ error: Error?) -> Void)) {
        readEntryWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Read an entry by its id
     - GET /mandants/{mandant}/entries/{id}
     - OAuth:
       - type: oauth2
       - name: oauth2

     - returns: RequestBuilder<Entry> 
     */
    open class func readEntryWithRequestBuilder() -> RequestBuilder<Entry> {
        let path = "/mandants/{mandant}/entries/{id}"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Entry>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: )
    }


    /**
     Read a specific enumerator
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func readEnumeratorById(completion: @escaping ((_ data: Enumerator?,_ error: Error?) -> Void)) {
        readEnumeratorByIdWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Read a specific enumerator
     - GET /mandants/{mandant}/enumerators/{type}/{id}
     - OAuth:
       - type: oauth2
       - name: oauth2

     - returns: RequestBuilder<Enumerator> 
     */
    open class func readEnumeratorByIdWithRequestBuilder() -> RequestBuilder<Enumerator> {
        let path = "/mandants/{mandant}/enumerators/{type}/{id}"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Enumerator>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: )
    }


    /**
     * enum for parameter mandant
     */
    public enum _readEnumeratorConstraintsByEnumeratorId: String { 
    }

    /**
     * enum for parameter enumeratorType
     */
    public enum _readEnumeratorConstraintsByEnumeratorId: EnumerationType { 
    }

    /**
     * enum for parameter enumeratorId
     */
    public enum _readEnumeratorConstraintsByEnumeratorId: ObjectId { 
    }

    /**
     * enum for parameter combinationConstraints
     */
    public enum _readEnumeratorConstraintsByEnumeratorId: Bool { 
    }

    /**
     Read constraints for a single enumerator
     
     - parameter mandant: (path) The mandant to operate on 
     - parameter enumeratorType: (path) The enumerator type to retrieve restrictions for 
     - parameter enumeratorId: (path) The id of the enumerator to retrieve restrictions for 
     - parameter combinationConstraints: (query) Includes/excludes the property combinationConstraints (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func readEnumeratorConstraintsByEnumeratorId(mandant: _readEnumeratorConstraintsByEnumeratorId, enumeratorType: _readEnumeratorConstraintsByEnumeratorId, enumeratorId: _readEnumeratorConstraintsByEnumeratorId, combinationConstraints: _readEnumeratorConstraintsByEnumeratorId? = nil, completion: @escaping ((_ data: EnumeratorConstraints?,_ error: Error?) -> Void)) {
        readEnumeratorConstraintsByEnumeratorIdWithRequestBuilder(mandant: mandant, enumeratorType: enumeratorType, enumeratorId: enumeratorId, combinationConstraints: combinationConstraints).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Read constraints for a single enumerator
     - GET /mandants/{mandant}/enumeratorConstraints/{enumeratorType}/{enumeratorId}
     - OAuth:
       - type: oauth2
       - name: oauth2
     
     - parameter mandant: (path) The mandant to operate on 
     - parameter enumeratorType: (path) The enumerator type to retrieve restrictions for 
     - parameter enumeratorId: (path) The id of the enumerator to retrieve restrictions for 
     - parameter combinationConstraints: () Includes/excludes the property combinationConstraints (optional)

     - returns: RequestBuilder<EnumeratorConstraints> 
     */
    open class func readEnumeratorConstraintsByEnumeratorIdWithRequestBuilder(mandant: _readEnumeratorConstraintsByEnumeratorId, enumeratorType: _readEnumeratorConstraintsByEnumeratorId, enumeratorId: _readEnumeratorConstraintsByEnumeratorId, combinationConstraints: _readEnumeratorConstraintsByEnumeratorId? = nil) -> RequestBuilder<EnumeratorConstraints> {
        var path = "/mandants/{mandant}/enumeratorConstraints/{enumeratorType}/{enumeratorId}"
        let mandantPreEscape = "\(mandant.rawValue)"
        let mandantPostEscape = mandantPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{mandant}", with: mandantPostEscape, options: .literal, range: nil)
        let enumeratorTypePreEscape = "\(enumeratorType.rawValue)"
        let enumeratorTypePostEscape = enumeratorTypePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{enumeratorType}", with: enumeratorTypePostEscape, options: .literal, range: nil)
        let enumeratorIdPreEscape = "\(enumeratorId.rawValue)"
        let enumeratorIdPostEscape = enumeratorIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{enumeratorId}", with: enumeratorIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "combinationConstraints": combinationConstraints?.rawValue
        ])

        let requestBuilder: RequestBuilder<EnumeratorConstraints>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: )
    }


    /**
     Create or update an entry by id
     
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateOrCreateEntryById(body: Entry? = nil, completion: @escaping ((_ data: Entry?,_ error: Error?) -> Void)) {
        updateOrCreateEntryByIdWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create or update an entry by id
     - PUT /mandants/{mandant}/entries/{id}
     - OAuth:
       - type: oauth2
       - name: oauth2
     
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Entry> 
     */
    open class func updateOrCreateEntryByIdWithRequestBuilder(body: Entry? = nil) -> RequestBuilder<Entry> {
        let path = "/mandants/{mandant}/entries/{id}"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Entry>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: )
    }

}
